### ISSUE TITLE
Switch to thread pool executors for parallel testing

### ISSUE THREAD

**Issue by vlavoie** [nuecho/rasa-integration-testing#13]
The tests are run asynchronously right now, but it would be cleaner to separate them into a thread pool that pick and run tests as they finish. This could potentially also fix the timeout problems.

Suggested by Florian in PR #10

**Comment by vlavoie** [comment]
Changing from async to a thread pool is actually fairly simple in the code but I did run into a weird issue. Due to threads being piped in python, objects need to be pickled. This limits what we can send which excludes anonymous functions and a lot of our custom objects and makes it a pain to just get it working, since we depend on runtime created object that cannot be pickled which will require some kind of workaround.

**Comment by fparga** [comment]
Maybe have a look at https://github.com/cloudpipe/cloudpickle it allows to pickle a lot more things than the native pickle module.

**Comment by vlavoie** [comment]
Interesting! This does seem to be meant for this specific use-case, I'll try it.

**Comment by vlavoie** [comment]
Just an update on this issue,

Using custom pickling is out of the question it seems. Serialization/deserialization is handled somewhere in the multiprocessing module, possibly outside of python and into cpython. I looked for alternatives and found out that it is possible to share thread objects through a [Proxy](https://docs.python.org/3/library/multiprocessing.html#proxy-objects) instead. However this creates a problem with the asyncio based runners, due to the way that asyncio interacts with the main thread. 

There are some recommendations on python's [official asyncio documentation](https://docs.python.org/3/library/asyncio-dev.html#asyncio-multithreading) which I am investigating. I could also completely ditch asyncio considering that each executor would only block and wait for a single thing at a time.
